name = "cf-worker-template"
account_id = ""
compatibility_date = "2022-12-01"
durable_objects.bindings = [
  { name = "Example", class_name = "Example" },
]

[miniflare]
durable_objects_persist = true

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./shim.mjs"

[vars]

[[migrations]]
tag = "v1"
new_classes = [
  "Example",
]
